name: Blog Build (Test)
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: NodeJS Setup
        uses: actions/setup-node@v4.0.0
        with:
          node-version: "20.9.0"
      - name: Ruby Setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.3"
      - name: Build site and pages
        run: |
          bundle install
          npm install
          ./build-styles.sh
          bundle exec jekyll build -s blog/ -d release && ls ./release