name: Blog Build
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: NodeJS Setup
        uses: actions/setup-node@v4.0.0
        with:
          node-version: "20.9.0"
      - name: Ruby Setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.3"
      - name: Build site and pages
        run: |
          bundle install
          bundle exec jekyll build -s blog/ -d release && ls ./release
      - name: Push Release Data
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GA_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "OttavaGA"
          git config --global user.email "admin@ottava.io"
          cd ./release
          echo "blog.ottava.io" > CNAME
          git init
          git add -A
          git commit -m "$(date)"
          git branch -M master
          git remote add origin git@github.com:ottavaio/ottavaio.github.io.git
          git push --force -u origin master